apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-abdf3998-9b98-449e-be1a-1176d660bf23-consumer1
  annotations:
    pv.kubernetes.io/provisioned-by: rook.cephfs.csi.ceph.com
  finalizers:
    - kubernetes.io/pv-protection
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node-user
      namespace: rook-ceph
    volumeAttributes:
      clusterID: rook-ceph
      fsName: sharedfs
      pool: sharedfs-replicated
      storage.kubernetes.io/csiProvisionerIdentity: 1678350415796-8081-rook-ceph.cephfs.csi.ceph.com
      subvolumeName: csi-vol-2714510b-be54-11ed-a902-babeba785e2c
      subvolumePath: /volumes/csi/csi-vol-2714510b-be54-11ed-a902-babeba785e2c/8d6f2629-2fce-43d8-8061-82a5821cf498
      rootPath: /volumes/csi/csi-vol-2714510b-be54-11ed-a902-babeba785e2c/8d6f2629-2fce-43d8-8061-82a5821cf498
      staticVolume: "true"
    volumeHandle: 0001-0009-rook-ceph-0000000000000001-2714510b-be54-11ed-a902-babeba785e2c-consumer1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-cephfs
  volumeMode: Filesystem
