apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: preload
  namespace: consumer1
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-cephfs
  volumeMode: Filesystem
  volumeName: pvc-abdf3998-9b98-449e-be1a-1176d660bf23-consumer1
