apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-04a64b17-2361-4071-a143-19a0d9571138-consumer2
  annotations:
    pv.kubernetes.io/provisioned-by: rook-ceph.cephfs.csi.ceph.com
  finalizers:
    - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 1Gi
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    volumeHandle: 0001-0009-rook-ceph-0000000000000001-cd7ec799-be6b-11ed-a902-babeba785e2c-consumer2
    volumeAttributes:
      clusterID: rook-ceph
      fsName: sharedfs
      pool: sharedfs-replicated
      storage.kubernetes.io/csiProvisionerIdentity: 1678350415796-8081-rook-ceph.cephfs.csi.ceph.com
      subvolumeName: csi-vol-cd7ec799-be6b-11ed-a902-babeba785e2c
      subvolumePath: >-
        /volumes/csi/csi-vol-cd7ec799-be6b-11ed-a902-babeba785e2c/4bcde7c9-0ade-4da4-ab4e-c4c8acf1cb90
      rootPath: >-
        /volumes/csi/csi-vol-cd7ec799-be6b-11ed-a902-babeba785e2c/4bcde7c9-0ade-4da4-ab4e-c4c8acf1cb90
      staticVolume: "true"
    nodeStageSecretRef:
      name: rook-csi-cephfs-node-user
      namespace: rook-ceph
    controllerExpandSecretRef:
      name: rook-csi-cephfs-provisioner
      namespace: rook-ceph
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-cephfs
  volumeMode: Filesystem
